Fix tarfile compatibility with Python<3.12
- tarsafe is an alternative to `tarfile.extractall(filter='tar' | 'data')`
  which the latter is only introduced since Python 3.12, our CI uses older py

* fixes error:

  TypeError: TarFile.extractall() got an unexpected keyword argument 'filter'

Signed-off-by: Onanii Yui <177497261+yui-onanii@users.noreply.github.com>